    
export const ACTION_RELOAD_DB_LIST = 'ACTION_RELOAD_DB_LIST';
export const ACTION_RELOAD_SERVER_INFO = 'ACTION_RELOAD_SERVER_INFO';
export const ACTION_LOAD_DB = 'ACTION_LOAD_DB';
export const ACTION_COLLECTION_QUERY = 'ACTION_COLLECTION_QUERY';