export const SET_RESIZER_POSITION = 'SET_RESIZER_POSITION';
export const SET_DB_LIST = 'SET_DB_LIST';
export const SET_SERVER_INFO = 'SET_SERVER_INFO';
export const SET_ACTIVE_DB = 'SET_ACTIVE_DB';
export const TOGGLE_LEFT_PANEL = 'TOGGLE_LEFT_PANEL';
export const UPDATE_DB_STATS = 'UPDATE_DB_STATS';
export const SET_ACTIVE_COLLECTION = 'SET_ACTIVE_COLLECTION';
export const SET_LOADING_DB = 'SET_LOADING_DB';
export const SET_COLLECTIONS_STATS = 'SET_COLLECTIONS_STATS';
export const SET_COLLECTION_QUERY_RESULT = 'SET_COLLECTION_QUERY_RESULT';
export const RESET_COLLECTION_QUERY_RESULT = 'RESET_COLLECTION_QUERY_RESULT';








