export const SET_RESIZER_POSITION = 'SET_RESIZER_POSITION';
export const SET_DB_LIST = 'SET_DB_LIST';
export const SET_SERVER_INFO = 'SET_SERVER_INFO';
export const SET_ACTIVE_DB = 'SET_ACTIVE_DB';
export const TOGGLE_LEFT_PANEL = 'TOGGLE_LEFT_PANEL';



