export const SET_RESIZER_POSITION = 'SET_RESIZER_POSITION';
export const SET_DB_LIST = 'SET_DB_LIST';
export const SET_SERVER_INFO = 'SET_SERVER_INFO';
export const SET_DB = 'SET_DB';
export const SET_COLLECTIONS = 'SET_COLLECTIONS';
export const UPDATE_DB_STATS = 'UPDATE_DB_STATS';


